"""Python SDK for the Prometheus Gateway inference API.

See ``spec/prometheus-gateway.md`` in the repository for the API contract this package implements.
"""

from axonium._version import __version__
from axonium.auth import TokenClaims, TokenSet
from axonium.client import AsyncAxonium, Axonium
from axonium.config import (
    DEFAULT_AUTH_BASE_URL,
    DEFAULT_GATEWAY_BASE_URL,
    AxoniumConfig,
    Timeouts,
)
from axonium.errors import (
    APIError,
    AuthTransportError,
    AxoniumError,
    BackendUnavailableError,
    BadRequestError,
    ConfigurationError,
    ContextExceededError,
    ForbiddenError,
    IdempotencyInProgressError,
    IdempotencyKeyReuseError,
    IdempotencyResponseNotRetainedError,
    InvalidClientError,
    InvalidIdempotencyKeyError,
    InvalidRequestError,
    InvalidScopeError,
    InvalidTokenError,
    MissingCredentialsError,
    ModalityMismatchError,
    ModelNotLoadedError,
    OAuthError,
    RateLimitError,
    RateLimitingUnavailableError,
    ServerError,
    SpendCapExceededError,
    StreamInterruptedError,
    TimeoutError,
    TokenExpiredError,
    TokenRevokedError,
    TransportError,
    UnauthorizedClientError,
    UnauthorizedError,
    UnknownInstanceError,
    UnknownModelError,
    UnsupportedFieldWarning,
    UnsupportedGrantTypeError,
    UnusedCredentialWarning,
    UpstreamError,
    UsageStoreUnavailableError,
    ValidationError,
)
from axonium.models.catalog import Model, ModelList
from axonium.models.chat import (
    ChatChoice,
    ChatCompletion,
    ChatCompletionChunk,
    ChoiceDelta,
    CompletionMessage,
    StreamChoice,
    Timings,
)
from axonium.models.common import APIObject, RateLimitSnapshot, ResponseMeta, Usage
from axonium.models.inference import (
    CreateEmbeddingResponse,
    Embedding,
    GeneratedImage,
    ImagesResponse,
)
from axonium.models.requests import (
    ChatCompletionRequest,
    ContentPart,
    EmbeddingsRequest,
    ImageGenerationRequest,
    Message,
)
from axonium.providers import AsyncTokenProvider, TokenProvider
from axonium.streaming import AsyncChatCompletionStream, ChatCompletionStream
from axonium.transport.retry import CooldownRegistry, RetryPolicy

__all__ = [
    "DEFAULT_AUTH_BASE_URL",
    "DEFAULT_GATEWAY_BASE_URL",
    "APIError",
    "APIObject",
    "AsyncAxonium",
    "AsyncChatCompletionStream",
    "AsyncTokenProvider",
    "AuthTransportError",
    "Axonium",
    "AxoniumConfig",
    "AxoniumError",
    "BackendUnavailableError",
    "BadRequestError",
    "ChatChoice",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionRequest",
    "ChatCompletionStream",
    "ChoiceDelta",
    "CompletionMessage",
    "ConfigurationError",
    "ContentPart",
    "ContextExceededError",
    "CooldownRegistry",
    "CreateEmbeddingResponse",
    "Embedding",
    "EmbeddingsRequest",
    "ForbiddenError",
    "GeneratedImage",
    "IdempotencyInProgressError",
    "IdempotencyKeyReuseError",
    "IdempotencyResponseNotRetainedError",
    "ImageGenerationRequest",
    "ImagesResponse",
    "InvalidClientError",
    "InvalidIdempotencyKeyError",
    "InvalidRequestError",
    "InvalidScopeError",
    "InvalidTokenError",
    "Message",
    "MissingCredentialsError",
    "ModalityMismatchError",
    "Model",
    "ModelList",
    "ModelNotLoadedError",
    "OAuthError",
    "RateLimitError",
    "RateLimitSnapshot",
    "RateLimitingUnavailableError",
    "ResponseMeta",
    "RetryPolicy",
    "ServerError",
    "SpendCapExceededError",
    "StreamChoice",
    "StreamInterruptedError",
    "TimeoutError",
    "Timeouts",
    "Timings",
    "TokenClaims",
    "TokenExpiredError",
    "TokenProvider",
    "TokenRevokedError",
    "TokenSet",
    "TransportError",
    "UnauthorizedClientError",
    "UnauthorizedError",
    "UnknownInstanceError",
    "UnknownModelError",
    "UnsupportedFieldWarning",
    "UnsupportedGrantTypeError",
    "UnusedCredentialWarning",
    "UpstreamError",
    "Usage",
    "UsageStoreUnavailableError",
    "ValidationError",
    "__version__",
]
