#!/usr/bin/env python3
"""
Ejemplo de uso del LLM Arch SDK

Este script demuestra cómo usar el SDK para hacer llamadas a un servidor LLM
con autenticación automática y manejo de errores.

NOTA: El SDK carga automáticamente el archivo .env del directorio actual.
Asegúrate de tener un .env con las credenciales necesarias.
"""

import logging
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import List
import json

load_dotenv()  # Carga variables de entorno desde .env

from llm_arch_sdk.adapters.llama_adapter import LlamaAdapter
from llm_arch_sdk.integrations.llm_runnable import LLMRunnable


# Configurar logging ANTES de importar el SDK para ver todos los mensajes
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""
    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")

class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""
    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(description="Specific, actionable suggestions for improving the code.")
    critique_summary: str = Field(description="A summary of the critique.")

class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""
    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(description="A summary of the changes made based on the critique.")


def generator_node(adapter, state):
    """Generates the initial draft of the code."""
    print("--- 1. Generating Initial Draft ---")
    llm = LLMRunnable(adapter=adapter, output_model=DraftCode)
    
    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation and an explanation.
    
    Request: {state['user_request']}
    """
    
    draft = llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.7, "max_tokens": 300})
    print("✅ Draft Generated:\n", draft)
    
    return {"draft": draft.model_dump()}

def critic_node(adapter, state):
    """Critiques the generated code for errors and inefficiencies."""
    print("--- 2. Critiquing Draft ---")
    critic_llm = LLMRunnable(adapter=adapter, output_model=Critique)
    
    code_to_critique = state['draft']['code']
    
    prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.
    
    Analyze the code for:
    1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?
    
    Provide a structured critique with specific, actionable suggestions.
    
    Code to Review:
    ```python
    {code_to_critique}
    ```
    """
    
    critique = critic_llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.9, "max_tokens": 900})
    print(f"✅ Critique : {critique}")
    
    return {"critique": critique.model_dump()}

def refiner_node(adapter, state):
    """Refines the code based on the critique."""
    print("--- 3. Refining Code ---")
    refiner_llm = LLMRunnable(adapter=adapter, output_model=RefinedCode)
    
    draft_code = state['draft']['code']
    critique_suggestions = json.dumps(state['critique'], indent=2)
    
    prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.
    
    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.
    
    **Original Code:**
    ```python
    {draft_code}
    ```
    
    **Critique and Suggestions:**
    {critique_suggestions}
    
    Please provide the final, refined code and a summary of the changes you made.
    """
    
    refined_code = refiner_llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.})
    
    print(f"✅ Refined Code:\n {refined_code}")
    
    return {"refined_code": refined_code.model_dump()} # Corrected: use .model_dump()


def main():
    print("🚀 Probando Agentes con LLM Arch SDK - LLMAdapter")
    
    try:
        state = {"user_request": "Escribe una función en Python que calcule el factorial de un número."}
        state.update(generator_node(adapter, state))
        state.update(critic_node(adapter, state))
        state.update(refiner_node(adapter, state))
        print("\n🎉 Código Final Refinado:\n", json.dumps(state, indent=2, ensure_ascii=False))
        
    except Exception as e:
        print(f"⚠️  Error al generar el código: {e}")

if __name__ == "__main__":
    main()