import json
import logging
from typing import List, Optional, TypedDict
from langgraph.graph import StateGraph, END

from dotenv import load_dotenv
from pydantic import BaseModel, Field


load_dotenv()  # Carga variables de entorno desde .env

from llm_arch_sdk.adapters.llama_adapter import LlamaAdapter
from llm_arch_sdk.integrations.llm_runnable import LLMRunnable

# Configurar logging ANTES de importar el SDK para ver todos los mensajes
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""
    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")

class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""
    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(description="Specific, actionable suggestions for improving the code.")
    critique_summary: str = Field(description="A summary of the critique.")

class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""
    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(description="A summary of the changes made based on the critique.")

class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""
    user_request: str
    draft: Optional[dict]
    critique: Optional[dict]
    refined_code: Optional[dict]
    
class JudgeLLMEvaluation(BaseModel):
    """Schema for evaluating a piece of code."""
    correctness_score: int = Field(description="Score from 1-10 on whether the code is logically correct.")
    efficiency_score: int = Field(description="Score from 1-10 on the code's algorithmic efficiency.")
    style_score: int = Field(description="Score from 1-10 on code style and readability (PEP 8). ")
    justification: str = Field(description="A brief justification for the scores.")

def make_generator_node(adapter):
    """Factory that returns a generator node bound to `adapter`."""
    def generator_node(state):
        print("--- 1. Generating Initial Draft ---")
        llm = LLMRunnable(adapter=adapter, output_model=DraftCode)
        prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
            Provide a simple, clear implementation and an explanation.
            
            Request: {state['user_request']}
            """
        draft = llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.7, "max_tokens": 300})
        print("✅ Draft Generated:\n", draft)
        return {"draft": draft.model_dump()}
    return generator_node

def make_critic_node(adapter):
    """Factory that returns a critic node bound to `adapter`."""
    def critic_node(state):
        print("--- 2. Critiquing Draft ---")
        critic_llm = LLMRunnable(adapter=adapter, output_model=Critique)
        code_to_critique = state['draft']['code']
        prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.
            Analyze the code for:
            1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
            2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?
            
            Provide a structured critique with specific, actionable suggestions.
            
            Code to Review:
            ```python
            {code_to_critique}
            ```
            """
        critique = critic_llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.9, "max_tokens": 900})
        print(f"✅ Critique : {critique}")
        return {"critique": critique.model_dump()}
    return critic_node

def make_refiner_node(adapter):
    """Factory that returns a refiner node bound to `adapter`."""
    def refiner_node(state):
        print("--- 3. Refining Code ---")
        refiner_llm = LLMRunnable(adapter=adapter, output_model=RefinedCode)
        draft_code = state['draft']['code']
        critique_suggestions = json.dumps(state['critique'], indent=2)
        prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.
            Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.
            
            **Original Code:**
            ```python
            {draft_code}
            ```
            
            **Critique and Suggestions:**
            {critique_suggestions}
            
            Please provide the final, refined code and a summary of the changes you made.
            """
        refined_code = refiner_llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.})
        print(f"✅ Refined Code:\n {refined_code}")
        return {"refined_code": refined_code.model_dump()}
    return refiner_node

def evaluate_code(adapter, code_to_evaluate: str):
    print("--- 4. Evaluating Code ---")
    judge_llm = LLMRunnable(adapter=adapter, output_model=JudgeLLMEvaluation)
    prompt = f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.
        
        Code:
        ```python
        {code_to_evaluate}
        ```
    """
    judge_evaluation = judge_llm.invoke({"messages": [{"role": "user", "content": prompt}], "temperature": 0.})
    print(f"✅ Judge Evaluation:\n {judge_evaluation}")
    return judge_evaluation
    


def main():
    print("🚀 Probando LLM Arch SDK con OpenAI - Ejemplo completo")
    try:
        # Crear adapter con parámetros personalizados
        graph_builder = StateGraph(ReflectionState)
        
        # Create adapter and compile the graph
        adapter = LlamaAdapter(model ="llama-7b")        

        # Bind adapter to node functions via factories
        graph_builder.add_node("generator", make_generator_node(adapter))
        graph_builder.add_node("critic", make_critic_node(adapter))
        graph_builder.add_node("refiner", make_refiner_node(adapter))
        
        # Define the workflow edges
        graph_builder.set_entry_point("generator")
        graph_builder.add_edge("generator", "critic")
        graph_builder.add_edge("critic", "refiner")
        graph_builder.add_edge("refiner", END)
        

        # Compile the graph
        reflection_app = graph_builder.compile()
        print("Reflection graph compiled successfully!")
        
        user_request = "Write a Python function to find the nth Fibonacci number."
        initial_input = {"user_request": user_request}
        
        # Corrected: This loop correctly captures the final, fully-populated state
        final_state = None
        for state_update in reflection_app.stream(initial_input, stream_mode="values"):
            final_state = state_update

        print("\n✅ Reflection workflow complete!")
        
        if final_state and 'draft' in final_state and 'refined_code' in final_state:
            print("--- Evaluating Initial Draft ---")
            initial_draft_evaluation = evaluate_code(adapter, final_state['draft']['code'])
            print(initial_draft_evaluation.model_dump()) # Corrected: use .model_dump()

            print("\n--- Evaluating Refined Code ---")
            refined_code_evaluation = evaluate_code(adapter, final_state['refined_code']['refined_code'])
            print(refined_code_evaluation.model_dump()) # Corrected: use .model_dump()
        else:
            print("Error: Cannot perform evaluation because the `final_state` is incomplete.")
        
        

    except Exception as e:
        print(f"❌ Error en la prueba: {e}")
        return 1
    return 0

if __name__ == "__main__":
    exit(main())