import json
import logging
from typing import List, Optional, TypedDict
from langfuse import propagate_attributes
from langgraph.graph import StateGraph, END

from dotenv import load_dotenv
from pydantic import BaseModel, Field

load_dotenv()  # Carga variables de entorno desde .env

from llm_arch_sdk.adapters.llama_adapter import LlamaAdapter
from llm_arch_sdk.integrations.agent import MiniAgent
from llm_arch_sdk.observability.helpers import new_session_id


# Configurar logging ANTES de importar el SDK para ver todos los mensajes
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""
    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")

class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""
    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(description="Specific, actionable suggestions for improving the code.")
    critique_summary: str = Field(description="A summary of the critique.")

class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""
    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(description="A summary of the changes made based on the critique.")

class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""
    user_request: str
    drafter: Optional[dict]
    critic: Optional[dict]
    refiner: Optional[dict]
    
class JudgeLLMEvaluation(BaseModel):
    """Schema for evaluating a piece of code."""
    correctness_score: int = Field(description="Score from 1-10 on whether the code is logically correct.")
    efficiency_score: int = Field(description="Score from 1-10 on the code's algorithmic efficiency.")
    style_score: int = Field(description="Score from 1-10 on code style and readability (PEP 8). ")
    justification: str = Field(description="A brief justification for the scores.")

# -------------------------
# Prompt builders para cada agente
# -------------------------

def build_generator_prompt(state):
    """Construye el prompt para generar código inicial."""
    
    return f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation and an explanation.
    
    Request: {state['user_request']}
    """

def build_critic_prompt(state):
    """Construye el prompt para criticar código."""
    
    code = state['drafter']['code']
    return f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.
    Analyze the code for:
    1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?
    
    Provide a structured critique with specific, actionable suggestions.
    
    Code to Review:
    ```python
    {code}
    ```
    """

def build_refiner_prompt(state):
    """Construye el prompt para refinar código basado en crítica."""
    
    draft_code = state['drafter']['code']
    critique = json.dumps(state['critic'], indent=2)
    return f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.
    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.
    
    **Original Code:**
    ```python
    {draft_code}
    ```
    
    **Critique and Suggestions:**
    {critique}
    
    Please provide the final, refined code and a summary of the changes you made.
    """

def build_evaluator_prompt(code_to_evaluate: str):
    """Retorna una función que construye el prompt de evaluación."""
    def _builder(state):
        # Para el evaluador, el código viene como parámetro externo, no del state
        return f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.
        
        Code:
        ```python
        {code_to_evaluate}
        ```
        """
    return _builder
    

@propagate_attributes(session_id=new_session_id(), version="3.0")
def main():
    print("🚀 Probando LLM Arch SDK con LangGraph - Patrón LLMAgent")
    try:
        # Crear adapter
        adapter = LlamaAdapter(model="llama-7b")        
        
        # Crear agentes LLM (mucho más conciso que las factories)
        agent_drafter = MiniAgent(
            adapter=adapter,
            name="drafter",
            output_model=DraftCode,
            prompt_builder=build_generator_prompt,
            temperature=0.7,
            max_tokens=300
        )
        
        agent_critic = MiniAgent(
            adapter=adapter,
            name="critic",
            output_model=Critique,
            prompt_builder=build_critic_prompt,
            temperature=0.9,
            max_tokens=900
        )
        
        agent_refiner = MiniAgent(
            adapter=adapter,
            name="refiner",
            output_model=RefinedCode,
            prompt_builder=build_refiner_prompt,
            temperature=0.0
        )
        
        # Construir grafo
        graph_builder = StateGraph(ReflectionState)
        
        # Agregar agentes como nodos (nombre especificado UNA vez)
        graph_builder.add_node("drafter", agent_drafter)
        graph_builder.add_node("critic", agent_critic)
        graph_builder.add_node("refiner", agent_refiner)
        
        # Definir flujo
        graph_builder.set_entry_point("drafter")
        graph_builder.add_edge("drafter", "critic")
        graph_builder.add_edge("critic", "refiner")
        graph_builder.add_edge("refiner", END)
        
        # Compilar y ejecutar
        reflection_app = graph_builder.compile()
        print("✅ Reflection graph compiled successfully!")
        
        user_request = "Write a Python function to find the nth Fibonacci number."
        final_state = None
        for state_update in reflection_app.stream({"user_request": user_request}, stream_mode="values"):
            final_state = state_update

        print("\n✅ Reflection workflow complete!")
        
        # Evaluación (nota: evaluator es diferente porque no usa state directamente)
        if final_state and 'drafter' in final_state and 'refiner' in final_state:
            print("\n--- Evaluating Initial Draft ---")
            agent_draft_evaluator = MiniAgent(
                adapter=adapter,
                name="evaluator.draft",
                output_model=JudgeLLMEvaluation,
                prompt_builder=build_evaluator_prompt(final_state['drafter']['code']),
                temperature=0.0
            )
            draft_eval = agent_draft_evaluator({})  # state vacío porque el código ya está en el prompt
            print(json.dumps(draft_eval['evaluator.draft'], indent=2))

            print("\n--- Evaluating Refined Code ---")
            agent_refined_evaluator = MiniAgent(
                adapter=adapter,
                name="evaluator.refined",
                output_model=JudgeLLMEvaluation,
                prompt_builder=build_evaluator_prompt(final_state['refiner']['refined_code']),
                temperature=0.0
            )
            refined_eval = agent_refined_evaluator({})
            print(json.dumps(refined_eval['evaluator.refined'], indent=2))
        else:
            print("Error: Cannot perform evaluation because the `final_state` is incomplete.")

    except Exception as e:
        print(f"❌ Error en la prueba: {e}")
        import traceback
        traceback.print_exc()
        return 1
    return 0

if __name__ == "__main__":
    exit(main())